"""empty message

Revision ID: 1f709e128b4f
Revises: d6803f68fbf2
Create Date: 2025-09-27 15:32:57.185320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f709e128b4f'
down_revision = 'd6803f68fbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id_creacion', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('usuario_id_modificacion', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id_modificacion'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id_creacion'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_id_modificacion')
        batch_op.drop_column('usuario_id_creacion')

    op.drop_table('usuarios')
    # ### end Alembic commands ###
