"""empty message

Revision ID: 568bce06198a
Revises: 1f709e128b4f
Create Date: 2025-09-27 16:09:05.692941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568bce06198a'
down_revision = '1f709e128b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_creacion', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('usuario_modificacion', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('pedidos_usuario_id_creacion_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('pedidos_usuario_id_modificacion_fkey'), type_='foreignkey')
        batch_op.drop_column('usuario_id_modificacion')
        batch_op.drop_column('usuario_id_creacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id_creacion', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('usuario_id_modificacion', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('pedidos_usuario_id_modificacion_fkey'), 'usuarios', ['usuario_id_modificacion'], ['id'])
        batch_op.create_foreign_key(batch_op.f('pedidos_usuario_id_creacion_fkey'), 'usuarios', ['usuario_id_creacion'], ['id'])
        batch_op.drop_column('usuario_modificacion')
        batch_op.drop_column('usuario_creacion')

    # ### end Alembic commands ###
