"""empty message

Revision ID: d6803f68fbf2
Revises: 9ce34cd09028
Create Date: 2025-09-27 14:43:59.113011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6803f68fbf2'
down_revision = '9ce34cd09028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_pedido', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('comision', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('comision')
        batch_op.drop_column('total_pedido')

    # ### end Alembic commands ###
