services:
  pedidos:
    build: .
    ports:
      - "8000:8000"
    networks:
      - monitoring
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  prometheus:
    image: prom/prometheus
    container_name: prometheus-monitor
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - monitoring
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - pedidos

  grafana:
    image: grafana/grafana
    container_name: grafana-monitor
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp:1025
      - GF_SMTP_FROM_ADDRESS=monitor@experimento.com
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - monitoring
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus

  smtp:
    image: axllent/mailpit
    container_name: smtp-monitor
    networks:
      - monitoring
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
    name: monitoring